version: '2'
services:
    qs_trabalho_disciplina-app:
        image: qs_trabalho_disciplina
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://qs_trabalho_disciplina-mysql:3306/qs_trabalho_disciplina?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    qs_trabalho_disciplina-mysql:
        extends:
            file: mysql.yml
            service: qs_trabalho_disciplina-mysql
